theme: jekyll-theme-minimal
title: Dr. Norris Lam
description: |
  New practice address
  Dr. Susan Capitelli & Associates in Richmond Hill
  (Yonge / Major Mackenzie)
  104 – 10350 Yonge St, Richmond Hill, ON L4C 5K9
  T: (905) 884-0061
github:
  is_user_page: false
