theme: jekyll-theme-minimal
title: "Dr. Norris Lam, Optometrist"
description: "Richmond Hill Eye Associates<br>(Yonge / Major Mackenzie) <br>104 – 10350 Yonge St <br>Richmond Hill, ON L4C 5K9 <br>T: (905) 884-0061</b>"
github:
  is_user_page: false
