theme: jekyll-theme-minimal
title: "Dr. Norris Lam, Optometrist"
description: "New practice address<br>Dr. Susan Capitelli & Associates in Richmond Hill<br>(Yonge / Major Mackenzie)<br>104 – 10350 Yonge St, Richmond Hill, ON L4C 5K9<br>T: (905) 884-0061"
github:
  is_user_page: false
